CREATE TABLE character (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(120) NOT NULL,
    archetype VARCHAR(80) NOT NULL,
    alignment VARCHAR(20) NOT NULL,
    backstory VARCHAR(2000),
    intelligence INTEGER NOT NULL,
    strength INTEGER NOT NULL,
    avatar_url VARCHAR(255),
    CONSTRAINT pk_character PRIMARY KEY (id)
);
